name: Build and publish multi-arch devcontainer to ghcr.io

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Pre-build devcontainer image for amd64 and arm64
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/mrxcitement/devc-cobol
          cacheFrom: ghcr.io/mrxcitement/devc-cobol
          push: always
